// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48izN-eQkG-q8i15MHVFigs5lovT0Tb8',
    appId: '1:917322099017:web:27987b7bc9c93df2d11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    authDomain: 'quick-cart-dca0e.firebaseapp.com',
    storageBucket: 'quick-cart-dca0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dn04RrfJVvcK4vGZgWCSF7scQKr4InY',
    appId: '1:917322099017:android:0942e82e88b65cfcd11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    storageBucket: 'quick-cart-dca0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5QNIbH0U-OetWbzs2NUBvluMntBisK0',
    appId: '1:917322099017:ios:3f4a5482357cf71fd11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    storageBucket: 'quick-cart-dca0e.appspot.com',
    iosBundleId: 'com.quickcart.app.quickCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe5QNIbH0U-OetWbzs2NUBvluMntBisK0',
    appId: '1:917322099017:ios:3f4a5482357cf71fd11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    storageBucket: 'quick-cart-dca0e.appspot.com',
    iosBundleId: 'com.quickcart.app.quickCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB48izN-eQkG-q8i15MHVFigs5lovT0Tb8',
    appId: '1:917322099017:web:92fc036459eb2e76d11298',
    messagingSenderId: '917322099017',
    projectId: 'quick-cart-dca0e',
    authDomain: 'quick-cart-dca0e.firebaseapp.com',
    storageBucket: 'quick-cart-dca0e.appspot.com',
  );
}
